name: widgets
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib
  - shapely
  - pandas
  - descartes
  - geopandas
  - ipyleaflet
  - ipykernel
  - jupyter
  - yaml
  - pip
  - pip:
    - descartes